services:
   db:
      environment:
         POSTGRES_USER: ${DB_USER}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: ${DB_NAME}
         POSTGRES_HOST: ${DB_HOST}
         POSTGRES_PORT: ${DB_PORT}

   app:
      environment:
         DB_USER: ${DB_USER}
         DB_PASSWORD: ${DB_PASSWORD}
         DB_NAME: ${DB_NAME}
         DB_HOST: ${DB_HOST}
         DB_PORT: ${DB_PORT}
