services:
   db:
      environment:
         POSTGRES_USER: ${DB_USER}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: ${DB_NAME}
      env_file: .env

   app:
      environment:
         DB_USER: ${DB_USER}
         DB_PASSWORD: ${DB_PASSWORD}
         DB_NAME: ${DB_NAME}
         DB_HOST: ${DB_HOST}
         DB_PORT: ${DB_PORT}
      env_file: .env
      ports:
         - '8089:8080'
